--
-- $Id$
--
create or replace directory DBAMGR.DBSYNC_LOGS_1 as '/u01/db_backup/dbsync/logs/edu-dbdg1.berrdev.uk__edust1'
/
CREATE TABLE DBAMGR.DBSYNC_LOGS_1
(
  LOGFILE_NAME         VARCHAR2(200 BYTE),
  STANDBY_SERVER       VARCHAR2(60 BYTE),
  DB_NAME              VARCHAR2(20 BYTE),
  STANDBY_SID          VARCHAR2(20 BYTE),
  APPLY_MODE           VARCHAR2(20 BYTE),
  START_DATE           VARCHAR2(20 BYTE),
  END_DATE             VARCHAR2(20 BYTE),
  OPEN_MODE            VARCHAR2(20 BYTE),
  STANDBY_CONFIG_FILE  VARCHAR2(200 BYTE),
  DROP_STANBY          VARCHAR2(20 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY DBSYNC_LOGS_1
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
    )
     LOCATION (DBSYNC_LOGS_1:'dbsync_details.txt')
  )
REJECT LIMIT 100
NOPARALLEL
NOMONITORING
/