--
-- Objects for dbsync logging in primary
--
-- $Id: //Infrastructure/Database/scripts/dbsync/database_code/primary_db_objects.sql#6 $
--
CREATE SEQUENCE DBAMGR.DBSYNC_STANDBY_HIST_SEQ
  START WITH 22215
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
/
CREATE SEQUENCE DBAMGR.DBSYNC_STANDBY_SEQ
  START WITH 101987
  MAXVALUE 9999999999999999999999999999
  MINVALUE 1
/
CREATE TABLE DBAMGR.DBSYNC_LOGS
(
  LOGFILE_NAME         VARCHAR2(200 BYTE),
  STANDBY_SERVER       VARCHAR2(60 BYTE),
  DB_NAME              VARCHAR2(20 BYTE),
  STANDBY_SID          VARCHAR2(20 BYTE),
  APPLY_MODE           VARCHAR2(20 BYTE),
  START_DATE           VARCHAR2(20 BYTE),
  END_DATE             VARCHAR2(20 BYTE),
  OPEN_MODE            VARCHAR2(20 BYTE),
  STANDBY_CONFIG_FILE  VARCHAR2(200 BYTE),
  DROP_STANBY          VARCHAR2(20 BYTE)
)
ORGANIZATION EXTERNAL
  (  TYPE ORACLE_LOADER
     DEFAULT DIRECTORY DBSYNC_LOGS
     ACCESS PARAMETERS 
       ( RECORDS DELIMITED BY NEWLINE
    FIELDS TERMINATED BY ','
   )
     LOCATION (DBSYNC_LOGS:'dbsync_details.txt')
  )
REJECT LIMIT 100
NOPARALLEL
NOMONITORING
/
CREATE TABLE DBAMGR.DBSYNC_STANDBY
(
  STANDBY_ID                   INTEGER,
  STANDBY_SERVER               VARCHAR2(100 BYTE),
  STANDBY_SID                  VARCHAR2(30 BYTE),
  LAST_FULL_REFRESH_START      DATE,
  LAST_FULL_REFRESH_END        DATE,
  LAST_FULL_REFRESH_STATUS     VARCHAR2(30 BYTE),
  LAST_FULL_REFRESH_LOG        CLOB,
  LAST_ROLLFORWARD_START       DATE,
  LAST_ROLLFORWARD_END         DATE,
  LAST_ROLLFORWARD_STATUS      VARCHAR2(30 BYTE),
  LAST_ROLLFORWARD_LOG         CLOB,
  STANDBY_APPLIED_REDOLOG_SEQ  INTEGER,
  STANDBY_APPLIED_UNTIL_SCN    NUMBER,
  STANDBY_APPLIED_UNTIL_DATE   DATE,
  PRIMARY_CURRENT_REDOLOG_SEQ  INTEGER
)
LOB (LAST_FULL_REFRESH_LOG) STORE AS (
  TABLESPACE  TBSDATA
  CACHE
)
LOB (LAST_ROLLFORWARD_LOG) STORE AS (
  TABLESPACE  TBSDATA
  CACHE
)
TABLESPACE TBSDATA
/
CREATE TABLE DBAMGR.DBSYNC_STANDBY_HIST
(
  HIST_ID                      INTEGER,
  STANDBY_ID                   INTEGER,
  ACTION                       VARCHAR2(30 BYTE),
  LOGFILE                      CLOB,
  LOGFILE_NAME                 VARCHAR2(300 BYTE),
  STATUS                       VARCHAR2(30 BYTE),
  STANDBY_APPLIED_REDOLOG_SEQ  INTEGER,
  STANDBY_APPLIED_UNTIL_SCN    NUMBER,
  STANDBY_APPLIED_UNTIL_DATE   DATE,
  PRIMARY_CURRENT_REDOLOG_SEQ  INTEGER,
  PRIMARY_CURRENT_SCN          INTEGER,
  PRIMARY_CURRENT_DATE         DATE,
  APPLY_START                  DATE,
  APPLY_END                    DATE
)
LOB (LOGFILE) STORE AS (
  TABLESPACE  TBSDATA
  ENABLE      STORAGE IN ROW
  CHUNK       8192
  RETENTION
  CACHE
)
TABLESPACE TBSDATA
/
